name: News Auto
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  run-intel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r python/requirements.txt
      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SHARED_APP_URL: ${{ secrets.SHARED_APP_URL }}
        run: python python/bot_engine.py
